### ISSUE TITLE
 extract encrypted rar file with encrypted content as file content

### ISSUE THREAD

**Issue by zhaoyong-zy** [junrar/junrar#17] opened 2018-08-28 06:03 UTC
There's a situation when i encrypted file with winRAR and select the "show password" button on the operation UI(as snapshort.bmp), when extract content from  the file(test.rar), it throwed the RarException but the "PipedOutputStream out" parameter has been assigned the wrong value which is encrypted content.
while another encrypted file without selected the "show password" button,  when extract it(1534240020.rar), it also thowed RarException but return nothing.

There behavied different at line 191 in ModelPPM decodeInit routine when it begin to unpack the file.  But i don't know the reason.

[test.zip](https://github.com/junrar/junrar/files/2330531/test.zip)

**Comment by 361442342** [comment] 2020-07-15 07:20
this project has not surpported to unpack the encrypted file.
```java
    private static File tryToExtract(
        final Log logger,
        final ExtractDestination destination,
        final Archive arch,
        final FileHeader fileHeader
    ) throws IOException, RarException {
        final String fileNameString = fileHeader.getFileNameString();
        //   look here
        if (fileHeader.isEncrypted()) {
            logger.warn("file is encrypted cannot extract: " + fileNameString);
            return null;
        }
        logger.info("extracting: " + fileNameString);
        logger.info("extracting: " + fileHeader.getFileNameW());
        if (fileHeader.isDirectory()) {
            return destination.createDirectory(fileHeader);
        } else {
            return destination.extract(arch, fileHeader);
        }
    }
````

**Comment by gotson** [comment] 2020-07-16 10:25
Closing, duplicate of #40

**Closed by gotson** 2020-07-16 10:25 UTC
