### ISSUE TITLE
com.github.junrar.exception.RarException: badRarArchive

### ISSUE THREAD

**Issue by lovejing0306** [junrar/junrar#27] opened 2018-12-29 09:04 UTC
请问这个问题怎么解决！

**Comment by beothorn** [comment] 2018-12-30 22:09
Does any software with rar support (7zip for example) is able to decompress your file?

Looking at the code it may be possible that your rar is invalid or has a version that is not supported.

**Comment by gotson** [comment] 2020-07-16 10:21
@lovejing0306 i am closing this since the issue is quite old. Please reopen if you still have the issue, and provide the file if possible so we can have a look.

**Closed by gotson** 2020-07-16 10:21 UTC
